#import "../../common/preamble.typ": *
#show: chapter-template.with(title: "Solids of Revolution")
#let ex = exercise.with(chapter: "Solids of Revolution")

// ── TEACHER'S NOTE ───────────────────────────────────────────
// LEVEL. This chapter is SHARED, by your decision, although only the
// SPF Lehrplan requires it: SPF Y4 1.2 names "Volumina von
// Rotationskörpern" explicitly, while GLF Y4 lists no application of
// integration beyond areas. Two consequences worth knowing:
//   * nothing later in the course depends on this chapter, so it is
//     the one place in the unit that can be cut for time in a GLF
//     class without breaking anything downstream;
//   * the only-high material (§6, rotation about the y-axis) and the
//     two parameter problems in §5 are where the SPF requirement
//     actually bites.
//
// §1 IS THE POINT OF THE CHAPTER, not the formula. Deriving
// V = π∫f(x)² dx by slicing into discs and recognizing a Riemann sum
// is the second time students see the "chop, approximate, sum, take
// the limit" argument, and the first time they see it produce
// something OTHER than an area. That transfer is the real content —
// the same argument gives arc length, surface area, work, centre of
// mass and much of physics. Say so; several of them will meet those
// integrals in Physik and will not otherwise connect them.
//
// The old LaTeX §9.3 states the theorem with two GeoGebra
// screenshots and no derivation. The screenshots are not reproduced
// here; a rotating solid is better demonstrated live in GeoGebra's 3D
// view than shown as two stills, and the description in §1 does not
// depend on them. If you want them back, the old files are
// img/solid_of_rotation*.png → suggested names
// solid-of-revolution-cylinder.png and
// solid-of-revolution-cone.png.

= Solids of Revolution

#only-theory[
  Take the graph of a function and spin it about the
  $x$\u{2011}axis. The curve sweeps out a surface, and the surface
  encloses a solid — a #vocab("solid of revolution",
  "Rotationskörper").

  A great many familiar shapes arise this way. Spin a horizontal line
  and you get a cylinder; spin a slanted line through the origin and
  you get a cone; spin a semicircle and you get a sphere. Spin
  something less familiar and you get a shape with no name and no
  volume formula — which is exactly the situation the integral was
  invented for.

  The method will be the one from the Riemann sum chapter, applied a
  second time. That repetition is the point of this chapter: the
  argument that computed an area computes volumes too, and after that
  it computes almost anything.
]

#epigraph(by: "Archimedes' tombstone, as described by Cicero")[
  A sphere inscribed in a cylinder, with the ratio $2 : 3$.
]

#objectives(
  [describe the solid obtained by rotating a given region about the
    $x$\u{2011}axis],
  [derive the disc formula by slicing a solid and recognizing a
    Riemann sum],
  bfkm[calculate the volume of a solid of revolution generated by one
    curve],
  [calculate the volume generated by the region between two curves],
  [recover the classical volume formulas for the cone, the sphere and
    the spherical cap],
  [determine a parameter so that a solid of revolution has a
    prescribed or extremal volume],
  obj(level: "high")[calculate the volume of a solid obtained by
    rotating a region about the $y$\u{2011}axis],
)

== Slicing a Solid into Discs

#only-theory[
  Cut the solid perpendicular to the axis of rotation, at some value
  of $x$. The cross-section is a *circle*, and its radius is the
  distance from the axis to the curve — that is, $f(x)$. So the
  cross-section has area
  $ pi dot (f(x))^2. $

  Now do to the solid exactly what we did to the region under a curve.
  Cut $[a, b]$ into $n$ strips of width $Delta x = (b - a) slash n$.
  Over one strip the radius barely changes, so that slab of the solid
  is almost a *disc* — a very short cylinder — of radius $f(x_k)$ and
  thickness $Delta x$, with volume
  $ pi dot (f(x_k))^2 dot Delta x. $
  Adding the slabs gives an approximation to the whole volume:
  $ V approx sum_(k = 1)^n pi dot (f(x_k))^2 dot Delta x. $

  That sum is a Riemann sum — of the function $pi dot f^2$. Letting
  $n -> oo$ turns it into an integral.

  #align(center)[
    #plot(
      xmin: -0.4, xmax: 3.4, ymin: -2.6, ymax: 2.6,
      width: 10, height: 5.5,
      axis-x-pos: "center", axis-y-pos: "left",
      xlabel: $x$, ylabel: $y$,
      xtick: (1, 2, 3), ytick: (-2, -1, 1, 2),
      show-origin: false,
      area-between(
        x => 0.4 * x + 1.0,
        x => -0.4 * x - 1.0,
        domain: (1.75, 2.05),
        color: rgb("#c94a00").lighten(55%),
      ),
      (
        fn: x => 0.4 * x + 1.0, domain: (0.0, 3.2),
        stroke: blue + 1.4pt,
        label: $f(x)$, label-pos: 0.97, label-side: "above-left",
      ),
      (
        fn: x => -0.4 * x - 1.0, domain: (0.0, 3.2),
        stroke: stroke(paint: blue.lighten(50%), thickness: 1pt, dash: "dashed"),
        label: $-f(x)$, label-pos: 0.97, label-side: "below-left",
      ),
      note([radius $f(x)$], (2.1, 0.9), anchor: "west", size: 8pt),
      note([thickness $Delta x$], (1.9, -1.9), anchor: "center", size: 8pt),
    )
  ]

  The dashed curve is the reflection of $f$ in the axis — it is not a
  second function, it is the far side of the same solid seen in cross
  section. The shaded strip is one disc: a circle of radius $f(x)$,
  seen edge-on, with thickness $Delta x$.
]

#keybox(title: "Volume of a solid of revolution")[
  If the graph of $f$ on $[a, b]$ is rotated about the
  $x$\u{2011}axis, the resulting solid has volume
  $ V = pi integral_a^b (f(x))^2 dif x. $
]

#warning[
  The integrand is $f(x)$ *squared*, and the squaring happens before
  the integration. So
  $ pi integral_a^b (f(x))^2 dif x
    eq.not pi dot (integral_a^b f(x) dif x)^2. $
  There is no relationship between the volume of the solid and the
  area of the region that generated it, and no amount of knowing one
  will give you the other.

  A second consequence of the square: the sign convention from the
  areas chapter does not apply here. Squaring destroys the sign, and a
  volume is always positive. There is nothing to split at the zeros of
  $f$.
]

#example(title: "Two shapes you already know")[
  *A cylinder.* Rotating the constant function $f(x) = r$ on $[0, h]$
  gives a cylinder of radius $r$ and height $h$:
  $ V = pi integral_0^h r^2 dif x = pi r^2 dot h. $
  Which is the formula you already knew.

  *A cone.* Rotating $f(x) = (r slash h) dot x$ on $[0, h]$ gives a
  cone of base radius $r$ and height $h$:
  $ V = pi integral_0^h (r/h)^2 x^2 dif x
    = pi r^2/h^2 dot [1/3 x^3]_0^h
    = 1/3 pi r^2 h. $
  Also as expected.

  The factor $1/3$ in the cone formula — which you were handed years
  ago with no justification — comes from integrating $x^2$. That is
  the whole reason it is a third and not something else.
]

=== Exercises

#ex(
  difficulty: 2,
  time: "20 min",
  calculator: false,
  hints: (
    [Square the function *first*, then integrate. Expanding a
      binomial before integrating is almost always easier than trying
      to be clever.],
    [In (c) the limits are not given: find the zeros of $f$ first.],
  ),
)[
  Each graph is rotated about the $x$\u{2011}axis on the given
  interval. Calculate the volume of the resulting solid.
  #auto-parts(
    2,
    [$f(x) = x^3$, #h(0.4em) $x in [1, 2]$],
    [$f(x) = x^2 + 1$, #h(0.4em) $0 lt.eq x lt.eq 1$],
    [$f: y = 3 x - x^2$, between the zeros of $f$],
    [$f: y = 1/x$, #h(0.4em) $x in [1, 4]$],
  )
][
  #auto-parts(
    2,
    [$pi integral_1^2 x^6 dif x = pi [1/7 x^7]_1^2
      = 127/7 pi$],
    [$pi integral_0^1 (x^4 + 2 x^2 + 1) dif x
      = pi (1/5 + 2/3 + 1) = 28/15 pi$],
    [The zeros are $0$ and $3$, and
      $ pi integral_0^3 (9 x^2 - 6 x^3 + x^4) dif x
        = 81/10 pi. $],
    [$pi integral_1^4 x^(-2) dif x = pi [-1/x]_1^4
      = 3/4 pi$],
  )

  Part (d) is worth comparing with the area of the same region, which
  is $ln(4) approx 1.39$. The volume is $3 pi slash 4 approx 2.36$,
  and there is no way to have predicted one from the other — squaring
  $1 slash x$ makes the far end of the solid thin out much faster than
  the region itself does.
]

#ex(
  difficulty: 2,
  time: "12 min",
  calculator: false,
  hints: (
    [Square the function first. The square of $1 slash sqrt(x)$ is
      pleasant.],
    [You will end up solving a logarithmic equation.],
  ),
)[
  The graph of $f: y = 1 / sqrt(x)$ is rotated about the
  $x$\u{2011}axis from $1$ to $a$. For which value of $a$ is the
  volume of the resulting solid equal to $3 pi$?
][
  Squaring gives $1 slash x$, so
  $ V = pi integral_1^a 1/x dif x = pi dot [ln(abs(x))]_1^a
    = pi dot ln(a), $
  using $ln(1) = 0$. Setting $pi ln(a) = 3 pi$ gives $ln(a) = 3$ and
  $ a = e^3 approx 20.09. $

  This is the one integral in the chapter where the square makes the
  problem *easier*: $1 slash sqrt(x)$ has an awkward antiderivative
  and $1 slash x$ has a famous one.
]

== The Classical Formulas

#only-theory[
  Two volumes you have used for years, both of which now become
  exercises.
]

#ex(
  difficulty: 3,
  time: "20 min",
  calculator: false,
  hints: (
    [A sphere of radius $r$ is generated by rotating the upper half of
      the circle $x^2 + y^2 = r^2$. Solve for $y$.],
    [A cap of height $h$ is the part of that solid between
      $x = r - h$ and $x = r$. Draw it.],
  ),
)[
  Use the disc formula to calculate the volume of
  #auto-parts(
    1,
    [a sphere of radius $r$;],
    [a spherical cap of radius $r$ and height $h$.],
  )
][
  #auto-parts(
    1,
    [The upper semicircle is $f(x) = sqrt(r^2 - x^2)$ on
      $[-r, r]$, and squaring removes the root entirely:
      $ V = pi integral_(-r)^r (r^2 - x^2) dif x
        = pi [r^2 x - 1/3 x^3]_(-r)^r
        = pi (2 r^3 - 2/3 r^3)
        = 4/3 pi r^3. $],
    [Same integrand, different limits — the cap occupies
      $r - h lt.eq x lt.eq r$:
      $ V = pi integral_(r - h)^r (r^2 - x^2) dif x
        = pi (r h^2 - 1/3 h^3)
        = 1/3 pi h^2 dot (3 r - h). $
      As a check, setting $h = 2 r$ (the whole sphere) gives
      $1/3 pi dot 4 r^2 dot r = 4/3 pi r^3$, agreeing with part
      (a).],
  )

  #heuristic("check an extreme or special case")

  The formula $4/3 pi r^3$ was found by Archimedes without calculus,
  by an argument comparing the sphere with a cylinder — the result he
  was proudest of, and the one he asked to have carved on his tomb.
  Here it takes three lines.
]

== Rotating the Region Between Two Curves

#only-theory[
  If two curves bound a region and that region is rotated, the solid
  has a hole through it: the outer curve sweeps the outside, the inner
  curve sweeps the cavity. Each cross-section is an *annulus* — a
  washer — with area
  $ pi dot (f(x))^2 - pi dot (g(x))^2, $
  where $f$ is the curve further from the axis.
]

#keybox(title: "The washer formula")[
  If the region between $f$ and $g$, with
  $abs(f(x)) gt.eq abs(g(x))$ on $[a, b]$, is rotated about the
  $x$\u{2011}axis:
  $ V = pi integral_a^b ((f(x))^2 - (g(x))^2) dif x. $

  Note the order of operations: *square, then subtract*. Writing
  $(f(x) - g(x))^2$ instead is a different and wrong quantity.
]

#warning[
  The condition is on $abs(f)$, not on $f$. What decides which curve is
  "outer" is the distance from the axis of rotation, and a curve at
  height $-5$ is further from the $x$\u{2011}axis than one at height
  $+2$. In every exercise here both curves stay on the same side of
  the axis, so the distinction does not bite — but it is worth knowing
  why the condition is stated the way it is.
]

#ex(
  difficulty: 2,
  time: "25 min",
  calculator: false,
  hints: (
    [Find the intersection points first — those are the limits.],
    [Decide which curve is further from the axis by testing one
      convenient value of $x$ between the intersections.],
  ),
)[
  The area enclosed by each pair of graphs is rotated about the
  $x$\u{2011}axis. Calculate the volume of the resulting solid.
  #auto-parts(
    1,
    [$y = x$ and $y = x^2$],
    [$y = x^2 + 3$ and $y = -2 x^2 + 6$],
    [$y = x^2$ and $y = sqrt(x)$],
  )
][
  #auto-parts(
    1,
    [They meet at $x = 0$ and $x = 1$; on that interval $x gt.eq x^2$,
      so the line is outer:
      $ V = pi integral_0^1 (x^2 - x^4) dif x
        = pi (1/3 - 1/5) = 2/15 pi. $],
    [Setting $x^2 + 3 = -2 x^2 + 6$ gives $3 x^2 = 3$, so
      $x = plus.minus 1$. At $x = 0$ the second curve gives $6$
      against $3$, so $-2 x^2 + 6$ is outer:
      $ V = pi integral_(-1)^1 ((-2 x^2 + 6)^2 - (x^2 + 3)^2) dif x
        = 176/5 pi. $
      Both functions are even, so the integral is twice the piece from
      $0$ to $1$ — worth using.],
    [They meet at $x = 0$ and $x = 1$; on that interval
      $sqrt(x) gt.eq x^2$, so the root is outer:
      $ V = pi integral_0^1 (x - x^4) dif x
        = pi (1/2 - 1/5) = 3/10 pi. $],
  )
]

== Parameters Again

#ex(
  difficulty: 3,
  time: "20 min",
  calculator: false,
  hints: (
    [Find the zeros in terms of $a$ first. Squaring the function
      absorbs the root neatly.],
    [Everything comes out as a power of $a$. Recognize $#num(15625)$.],
  ),
)[
  The graph of
  $ f: y = (x^2 - a dot x) dot sqrt(x), quad a > 0 $
  is rotated about the $x$\u{2011}axis between its zeros. Determine
  $a$ so that the volume of the resulting solid is
  $ 3125/12 dot pi. $
][
  The domain requires $x gt.eq 0$, and the zeros are $x = 0$ and
  $x = a$. Squaring:
  $ (f(x))^2 = (x^2 - a x)^2 dot x
    = x^5 - 2 a x^4 + a^2 x^3. $
  Integrating from $0$ to $a$:
  $ V = pi [1/6 x^6 - 2/5 a x^5 + 1/4 a^2 x^4]_0^a
    = pi a^6 dot (1/6 - 2/5 + 1/4)
    = pi a^6 / 60. $
  Setting this equal to $3125 pi slash 12$:
  $ a^6 = 3125/12 dot 60 = #num(15625) = 5^6
    quad ==> quad a = 5. $

  The arithmetic was arranged to come out exactly, which is the usual
  sign that the integral was set up correctly.
]

#ex(
  difficulty: 3,
  time: "25 min",
  calculator: true,
  level: "high",
  hints: (
    [Compute the volume as a function of $a$ first. The constant
      $1 slash (a - 1)^2$ comes straight out of the integral.],
    [Then it is an optimization problem from last year: differentiate
      with respect to $a$ and set to zero.],
  ),
)[
  The graph of
  $ f: y = (a - x) / (a - 1) dot x^2, quad a > 1 $
  is rotated about the $x$\u{2011}axis between its zeros. For which
  value of $a$ is the volume of the resulting solid minimal?
][
  The zeros are $x = 0$ (double) and $x = a$. Squaring and pulling the
  constant out:
  $ V(a) = pi/(a - 1)^2 integral_0^a (a - x)^2 dot x^4 dif x. $
  Expanding the integrand as $a^2 x^4 - 2 a x^5 + x^6$ and
  integrating:
  $ V(a) = pi/(a-1)^2 dot a^7 dot (1/5 - 1/3 + 1/7)
    = (pi a^7) / (105 dot (a - 1)^2). $

  Now minimize. Differentiating the quotient $a^7 slash (a-1)^2$:
  $ (7 a^6 (a - 1)^2 - a^7 dot 2 (a - 1)) / (a - 1)^4
    = (a^6 dot (5 a - 7)) / (a - 1)^3, $
  which vanishes for $a > 1$ only at
  $ a = 7/5 = 1.4. $
  The derivative changes from negative to positive there, so it is a
  minimum.

  #heuristic("work backwards from the goal")

  Two years of calculus in one problem: an integral produces a
  function of the parameter, and a derivative then minimizes it.
]

#only-high[
  == Rotating About the $y$\u{2011}axis

  Nothing about the derivation privileged the $x$\u{2011}axis. Slice
  perpendicular to whatever axis you are rotating about, and the same
  argument applies — but the slices are now horizontal, so everything
  must be expressed as a function of $y$.

  #keybox(title: [Rotation about the $y$\u{2011}axis])[
    If a curve is written as $x = g(y)$ and the region between it and
    the $y$\u{2011}axis, for $c lt.eq y lt.eq d$, is rotated about the
    $y$\u{2011}axis, the volume is
    $ V = pi integral_c^d (g(y))^2 dif y. $
  ]

  The practical step is *inverting* the function: given $y = f(x)$,
  solve for $x$. That is not always possible in closed form, which is
  the honest reason this method is less commonly used than the first.

  #example(title: "The same curve, two different solids")[
    Take $y = x^2$ for $0 lt.eq x lt.eq 1$.

    Rotated about the $x$\u{2011}axis:
    $ V = pi integral_0^1 x^4 dif x = pi/5. $

    Rotated about the $y$\u{2011}axis, the curve is $x = sqrt(y)$ with
    $0 lt.eq y lt.eq 1$:
    $ V = pi integral_0^1 (sqrt(y))^2 dif y
      = pi integral_0^1 y dif y = pi/2. $

    Same curve, same interval, and volumes differing by a factor of
    $2.5$. The axis of rotation is not a detail.
  ]

  #ex(difficulty: 3, time: "15 min", calculator: false, level: "high")[
    The region bounded by $y = x^3$, the $y$\u{2011}axis and the line
    $y = 8$ is rotated about the $y$\u{2011}axis. Calculate the volume
    of the resulting solid.
  ][
    Solving for $x$ gives $x = root(3, y) = y^(1/3)$, and $y$ runs
    from $0$ to $8$:
    $ V = pi integral_0^8 (y^(1/3))^2 dif y
      = pi integral_0^8 y^(2/3) dif y
      = pi [3/5 y^(5/3)]_0^8
      = 3/5 pi dot 32 = 96/5 pi. $
    Here $8^(5/3) = (root(3, 8))^5 = 2^5 = 32$ — again a set of
    numbers chosen to come out whole.
  ]
]

#look-ahead(
  title: "The same argument, over and over",
  preview: "what integrals are for",
)[
  Look back at what §1 actually did. It cut a quantity into many small
  pieces, approximated each piece by something simple, added them up,
  and took a limit. That is precisely the argument of the Riemann sum
  chapter, and it produced a volume rather than an area only because
  the pieces being added were discs rather than rectangles.

  The same argument, with different pieces, gives the length of a
  curve, the surface area of a solid, the work done by a variable
  force, the centre of mass of an object, the total charge in a
  region, and a large fraction of the mathematics in your physics
  course. Whenever a quantity accumulates continuously, the same four
  steps apply.

  That is what an integral *is*. Not "the opposite of a derivative" —
  that is a theorem about integrals, not their meaning.
]

#ai-box(role: "Explainer")[
  Ask an AI assistant why the volume of a cone is exactly one third of
  the cylinder that contains it, and require the explanation to use
  the disc formula rather than quoting the result.

  Then ask the harder question: *why is the sphere exactly two thirds
  of its circumscribed cylinder?* Check the answer by computing both
  volumes yourself — the cylinder has radius $r$ and height $2 r$.
  This is the relationship Archimedes had carved on his tombstone, and
  the fact that it drops out of a three-line integral is worth
  appreciating rather than merely verifying.
]

#print-hints()
#print-vocab()
